# Generated by Django 3.2.6 on 2021-08-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('sex', models.BooleanField(default=False, verbose_name='性别')),
                ('res_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('email', models.EmailField(default='x@x', max_length=254, verbose_name='邮箱')),
                ('info', models.CharField(default='', max_length=500, verbose_name='个人介绍')),
            ],
            options={
                'verbose_name': '个人资料',
                'verbose_name_plural': '个人资料',
                'db_table': 'User_info',
            },
        ),
    ]
