# Generated by Django 3.2.6 on 2021-09-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210831_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
    ]
