# Generated by Django 3.2.6 on 2021-09-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_info_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='name',
            new_name='username',
        ),
    ]
