# Generated by Django 3.2.6 on 2021-09-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_name_user_info_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='img',
            field=models.ImageField(default='', upload_to='picture', verbose_name='头像'),
        ),
    ]
